image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt update && apt -y install make
  script:
    - make clean
    - make

test:
  stage: test
  script:
    - mvn test

