image: maven:latest

stages:
  - build
  - test

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install build-essential
  script:
    - make clean
    - make

test:
  stage: test
  script:
    - mvn test

